name: Site Name
birthdate: 1900-01-01
services:
  flickr:
    api_key: your_flickr_api_key_goes_here
    users: #whitelist of flickr feeds to check
      - nsid: flickr_nsid
        tags: 
          - tag1
          - tag2
      - nsid: another_flickr_nsid
        tags:
          - tag1
          - tag3
  twitter:
    users: #whitelist of twitter users to check
      - username: username
        password: password
        include:  
      - username: another_username
        password: password
        include:  optional_text_that_must_be_in_each_tweet
      - username: yet_another_username
        password: password
        include:  optional_text_that_must_be_in_each_tweet
