name: Felix Oye
siteslug: felixoye
about_text: "My name is Felix Oye and this is my little corner of the web. For all of my adoring fans around the world, I built this site so you can keep with my continuing adventures."
avatar: http://farm4.static.flickr.com/3257/3169689939_6ef957dcf4_s.jpg
group_stream_by: "age_month"
birthdate: 2008-08-02
google_analytics_id: "UA-1807438-5"
services:
  flickr:
    users: #whitelist of flickr feeds to check
      - nsid:     12021774@N05
        username: philoye
        tags:     "felix, felixoye"
      - nsid:     30853535@N00
        username: jenmonsta
        tags:     "felix, felixoye"
  twitter:
    users: #whitelist of twitter users to check
      - username: felixoye
        include:  
        exclude:   
      - username: jessicaoye
        include:  @felixoye
        exclude:   
      - username: simonoye
        include:  @felixoye
        exclude:   
      - username: philoye
        include:  @felixoye
        exclude:   
      - username: jenioye
        include:  @felixoye
        exclude:   
