name: Jessica Oye
siteslug: jessicaoye
about_text: "My name is Jessica Oye and this is my little corner of the web. For all of my adoring fans around the world, I built this site so you can keep with my continuing adventures."
avatar: http://farm4.static.flickr.com/3258/3170518772_83651f3958_s.jpg
group_stream_by: "age_month"
birthdate: 2008-08-02
google_analytics_id: "UA-1807438-6"
services:
  flickr:
    users: #whitelist of flickr feeds to check
      - nsid:     12021774@N05
        username: philoye
        tags:     "jessica, jessicaoye"
      - nsid:     30853535@N00
        username: jenmonsta
        tags:     "jessica, jessicaoye"
  twitter:
    users: #whitelist of twitter users to check
      - username: felixoye
        include:  @jessicaoye
        exclude:   
      - username: jessicaoye
        include:  
        exclude:   
      - username: simonoye
        include:  @jessicaoye
        exclude:   
      - username: philoye
        include:  @jessicaoye
        exclude:   
      - username: jenioye
        include:  @jessicaoye
        exclude:   
