site_name: The Oye Kids
site_slug: oyekids
about_text: "This is the home of Simon, Jessica, and Felix. Hopefully, it gives a taste of the chaos that the three of us can produce."
avatar: http://farm4.static.flickr.com/3636/3556138250_0ede1e9e86_s.jpg
group_stream_by: "calendar_month"
birthdate: "2006-12-29"
google_analytics_id: "UA-1807438-4"
reinvigorate_id: "a882g-8201k8xk9e"
flickr_sources:
  - nsid:     12021774@N05
    username: philoye
    tags:     "jessica, jessicaoye, felix, felixoye, simon, simonoye"
  - nsid:     30853535@N00
    username: jenioye
    tags:     "jessica, jessicaoye, felix, felixoye, simon, simonoye"
twitter_sources:
  - username: felixoye
    include:  
  - username: jessicaoye
    include:  
  - username: simonoye
    include:  
  - username: philoye
    include:  "@jessicaoye, @felixoye, @simonoye"
  - username: jenioye
    include:  "@jessicaoye, @felixoye, @simonoye"
