site_name: Simon Oye
site_slug: simonoye
about_text: "Hi, my name is Simon. I entered the world on 29&nbsp;December&nbsp;2006 and I live in Sydney with my parents and twin sister and brother <a href='http://jessicaoye.com'>Jessica</a> and <a href='http://felixoye.com'>Felix</a>. Visit regularly to keep up with my adventures."
avatar: http://farm2.static.flickr.com/1188/3170516144_607d4ed43c_s.jpg
group_stream_by: "age_month"
birthdate: 2006-12-29
google_analytics_id: "UA-1807438-2"
reinvigorate_id: "xs9q3-82936v5u1r"
flickr_sources:
  - nsid:     12021774@N05
    username: philoye
    tags:     "simon, simonoye"
  - nsid:     30853535@N00
    username: jenioye
    tags:     "simon, simonoye"
twitter_sources:
  - username: felixoye
    include:  @simonoye
    exclude:   
  - username: jessicaoye
    include:  @simonoye
    exclude:   
  - username: simonoye
    include:  
    exclude:  
  - username: philoye
    include:  @simonoye
    exclude:  
  - username: jenioye
    include:  @simonoye
    exclude:  